import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ScreenContainer } from '../components/ScreenContainer';
import { COLORS, SPACING } from '../constants/theme';
import { createPlant, deletePlant, listPlants, type Plant, waterPlant } from '../services/plantsService';
const DAY = 86400000;
const dueAt = (p: Plant) => new Date(p.lastWateredAt || p.createdAt).getTime() + p.wateringEveryDays * DAY;
export function PlantsScreen() {
 const [plants,setPlants]=useState<Plant[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[name,setName]=useState(''),[days,setDays]=useState('7');
 const load=useCallback(async()=>{setLoading(true);try{setPlants(await listPlants())}catch(e){Alert.alert('Plants unavailable',e instanceof Error?e.message:'Try again later.')}finally{setLoading(false)}},[]); useEffect(()=>{void load()},[load]); const now=Date.now();
 const add=async()=>{const n=Number(days);if(!name.trim()||!Number.isInteger(n)||n<1)return Alert.alert('Check plant details','Enter a name and a whole number of days.');try{const plant=await createPlant({name:name.trim(),wateringEveryDays:n});setPlants(p=>[plant,...p]);setOpen(false);setName('');setDays('7')}catch(e){Alert.alert('Could not add plant',e instanceof Error?e.message:'Save a location first.')}};
 return <ScreenContainer scrollable contentStyle={s.page}><View style={s.header}><Text style={s.title}>Plant care</Text><Pressable onPress={()=>setOpen(true)} style={s.button}><Text style={s.buttonText}>Add plant</Text></Pressable></View>{loading?<ActivityIndicator color={COLORS.primary}/>:plants.map(p=>{const due=dueAt(p)<=now+DAY;return <View key={p.id} style={s.card}><Text style={s.name}>🌿 {p.name}</Text><Text style={s.muted}>{p.species||'Plant'} · {p.location}</Text><Text style={[s.status,due&&s.due]}>{due?'Needs water':'On schedule'} · every {p.wateringEveryDays} days</Text><View style={s.actions}><Pressable onPress={()=>void waterPlant(p.id).then(x=>setPlants(all=>all.map(v=>v.id===p.id?x:v))).catch(()=>Alert.alert('Could not update plant'))} style={s.button}><Text style={s.buttonText}>Water</Text></Pressable><Pressable onPress={()=>Alert.alert('Remove plant?',`Remove ${p.name}?`,[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>void deletePlant(p.id).then(()=>setPlants(all=>all.filter(v=>v.id!==p.id))).catch(()=>Alert.alert('Could not remove plant'))}])}><Text style={s.remove}>Remove</Text></Pressable></View></View>})}{!loading&&!plants.length?<Text style={s.muted}>No plants yet. Add one to begin.</Text>:null}<Modal visible={open} transparent><View style={s.modalBg}><View style={s.modal}><Text style={s.title}>Add a plant</Text><TextInput value={name} onChangeText={setName} placeholder="Plant name" placeholderTextColor="#82909B" style={s.input}/><TextInput value={days} onChangeText={setDays} keyboardType="number-pad" placeholder="Water every (days)" placeholderTextColor="#82909B" style={s.input}/><View style={s.actions}><Pressable onPress={()=>setOpen(false)}><Text style={s.muted}>Cancel</Text></Pressable><Pressable onPress={()=>void add()} style={s.button}><Text style={s.buttonText}>Save</Text></Pressable></View></View></View></Modal></ScreenContainer>
}
const s=StyleSheet.create({page:{paddingTop:SPACING.m,gap:SPACING.m},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:COLORS.textPrimary,fontSize:26,fontWeight:'700'},card:{backgroundColor:COLORS.backgroundCard,padding:SPACING.m,borderRadius:12,gap:SPACING.xs},name:{color:COLORS.textPrimary,fontSize:18,fontWeight:'600'},muted:{color:COLORS.textSecondary},status:{color:COLORS.success},due:{color:COLORS.warning},actions:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:SPACING.s},button:{backgroundColor:COLORS.primary,paddingHorizontal:SPACING.m,paddingVertical:SPACING.s,borderRadius:8},buttonText:{color:COLORS.white,fontWeight:'700'},remove:{color:COLORS.danger},modalBg:{flex:1,justifyContent:'center',padding:SPACING.m,backgroundColor:'rgba(0,0,0,.7)'},modal:{backgroundColor:COLORS.backgroundCard,padding:SPACING.l,borderRadius:12,gap:SPACING.m},input:{borderColor:COLORS.border,borderWidth:1,borderRadius:8,padding:SPACING.m,color:COLORS.textPrimary}});
